### ISSUE TITLE
Package categories

### ISSUE THREAD

**Issue by christian34** [openalea/openalea.rtfd.io#5]
The current categories for browsing packages are:
    Plant representation and analysis
    Modeling
    Simulation
    Phenotyping

To me simulation and modelling are not informative enough to understand at first glance what is behind, and grouping 'plant representation' and 'analysis' seems to me mixing  heterogenous packages. (Phenotyping is okay ;-) !)
My personal view of package categories is (order to be defined):
 - Modelling with OpenAlea (or Modelling environnement or Modelling toolbox) : MTG, Lpy, PlantGL, Openalea core, Visualea, ...
 - Plant models [may be further splited into static / dynamic or  'Structural Plant Model' and 'Functional-Structural Plant models']: weber-Pen, adel, mappleT, cereals,mango, Topvine,....
 - Plant biophysics : Hydroshoot, Caribu, astk, [ + in the near future assimilate_partitionning, photosynhesis...]]
 - Phenotyping (or Phenotyping & Data analysis) : phenomenal, eartrack, 

May be 'epidemics' can also be identified, or grouped with biophysics (if we find a more generic term)

**Comment by bbrument** [comment]
The categories have been updated. What do you think about it now ?

**Comment by pradal** [comment]
I like it. There are some problems of rendering (from mango everything is centered).
I will add only packages that are on OpenAlea, not all the packages.
This will ensure that packages are available as OpenSource and maintain.

**Comment by bbrument** [comment]
Okay so all the packages coming from openalea-incubator should not be displayed on this page ? Only the OpenAlea ones, is that it ?

**Comment by bbrument** [comment]
Idk where are the repositories for cereals, mango and topvine. Are they from openalea or openalea-incubator ?

**Comment by pradal** [comment]
They are not yet released or available on github.
So create an issue and I will assign the developper.

**Comment by pradal** [comment]
Closed due to inactivity
