### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by pomme-abricot** [openalea/openalea.rtfd.io#9]
Hi,

- It might be usefull to add a link to the wiki page from the reademe.rst (as usually we go straight to the readthedoc not the wiki).
- In the coding guidelines, i would put the directive at the begining of each section instead of putting them at the end. (Maybe also put a link there to an example pkg or explicitly say to check there for more info)
- Continouous integration needs to be completed. (at least put a link to Travis or Appveyor wiki)
- In the documentationguidelines: 1) add a section for sphinx? (as it is not the only solution) 2) Add a link to the openalea (it would prevent people getting a low res or outdated image on google).
- The API documentation guideline needs to be completed.
- The Readme guidelines are not followed in this package.
- Maybe add a package template as example, with the recommended structure for the namespace & doc.

**Comment by Wilgawox** [comment]
@pomme-abricot 
Thanks for your comments ! Here what I did :
- There is now a link to the wiki in the README
- The directive is now at the top of the section for more visibility
- CI is for now limited to link to the doc and websites ( will get to finish it later)
- Added a little section to explain that we uses sphinx and readthedocs (with links) + added a link to the logo on the official website
- No change to API doc for now
- Currently creating the example package, the I will update the README

**Comment by pomme-abricot** [comment]
Why is "bug" in the readme guideline?

**Comment by pomme-abricot** [comment]
Add sponsorts in readme guidelines

**Comment by Wilgawox** [comment]
All the work is done, though the README is not complete. I will be closing the issue, but feel free to reopen it if something need improvement.
